name: Ecommerce App CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    # This job will run on every push and pull request to the main branch. It will check out the code, set up Node.js, install dependencies, run tests, and build the application.
    runs-on: ubuntu-latest
    steps:
      #step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
      #step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      #step 3: Install dependencies
      - name: Install dependencies
        working-directory: ecommerce-app
        run: npm install
      #step 4: Run tests
      - name: Run tests
        working-directory: ecommerce-app
        run: npm test
      #step 5: Build application
      - name: Build application
        working-directory: ecommerce-app
        run: npm run build
